/*
  A manual e2e test for creating a new 'Order'. In normal operation, the creation
  of the Order is generated by the webhook from the P2WDB. It's not something
  that involves a human. This script simulates the webhook coming from P2WDB.

  Ensure the REST API is up an running before running this test.
*/

const axios = require('axios')

const LOCALHOST = 'http://localhost:5700'

async function start () {
  try {
    const mockOffer = {
      appId: 'swapTest555',
      data: {
        messageType: 1,
        messageClass: 1,
        tokenId: '2jgTFB6MM4vwLzUNWFYGPfyeQfpLaEqj4XWku6FoW7vaGrrEd5',
        buyOrSell: 'sell',
        rateInSats: 3000000,
        minSatsToExchange: 10,
        numTokens: 1.7,
        utxoTxid: '2HHYCuAfLhqUtiKsNdK9rsasfmHbJFLW8igri4Hb61hdBvYpyN',
        utxoVout: 1,
        txHex: '00000001ed5f38341e436e5d46e2bb00b45d62ae97d1b050c64bc634ae10626739e35c4b0000000121e67317cbc4be2aeb00677ad6462778a8f52274b9d605df2591b23027a87dff0000000700000000002dc6c000000000000000000000000100000001899c60081d331395dc13f93149f3ddc6ab7d559b00000001a8ac6a1a0a433325076c7a30a73ce7cb670c6cf0246f312ac23eb9e0a03f51fa00000001e49b53ab21c6f7b10bf8efb3e3bc0059954989b3d481a9cb862f4b0b7d57c6450000000500000000000000aa000000010000000000000000',
        addrReferences: '{"2HHYCuAfLhqUtiKsNdK9rsasfmHbJFLW8igri4Hb61hdAYsh12":"X-avax12jl70wc45qxqk2xk4wt7hv7ev5veea5e2vgt8g"}',
        hdIndex: 1
      },
      timestamp: '2022-01-18T05:43:57.471Z',
      localTimeStamp: '1/18/2022, 1:43:57 AM',
      hash: 'zdpuAzFjM9oPCwXW5U2GD7bxQARY4fVziH1x1cESqyLFt6Xo2',
      txid: '9d72dd8b44ae992e17b8234843158528b12d81b1f7795521d7e3d164b6ea8f14'
    }

    const options = {
      method: 'post',
      url: `${LOCALHOST}/order`,
      data: mockOffer
    }

    const result = await axios(options)
    console.log('result.data: ', result.data)
  } catch (err) {
    console.log(err)
  }
}
start()
